def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]

pipeline {
    agent any
    tools {
        maven "MAVEN3.9.9"
        jdk "JDK17"
    }
    

    environment {
        cluster = "vproappProd65"
        service = "vproapptask-service-prod"
    }

    stages {
        stage('Deploy to Prod'){
            withAWS(credentials: 'awscred', region: 'us-east-1') {
                sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
            }
        }
    }

    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#all-mydevops',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }  
    }
    
}